version: '3.3'

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    providers:
      docker:
        endpoint: "tcp://127.0.0.1:2377"
        swarmMode: true
        exposedbydefault: false
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "433:433"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  reverseproxy-nw:
    external: true
  traefik-reverse-proxy_default:
    external: true