version: '3.3'

services:
  vaultwarden:
    image: 'vaultwarden/server:latest'
    restart: unless-stop
    deploy:
      replicas: 1
    ports:
      - 8000:80
    volumes:
      - vaultwarden:/data

volumes:
    vaultwarden: {}