version: '3.3'

services:
  resume:
    image: ghcr.io/jr33d/resume-jreed-me:latest
    restart: unless-stopped
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.resume.rule=Host(`jreed.me`)
        - traefik.http.services.resume_resume.loadbalancer.server.port=3000
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      SENDGRID_API_KEY:
      CONTACT_EMAIL:
      APP_EMAIL:
    networks:
      - web-servers

networks:
  web-servers:
    external: true